set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_C_FLAGS "/fsanitize=address ${VCPKG_C_FLAGS}")
set(VCPKG_CXX_FLAGS "/fsanitize=address ${VCPKG_CXX_FLAGS}")
set(VCPKG_LINKER_FLAGS "/INCREMENTAL:NO")
